-- =============================================================================
-- Outreach Platform — 058 billing v2: price book, plan features and early-supporter tiers
-- GENERATED by scripts/pricing-sync.mjs from pricing/v1.json. Do not edit: change the JSON and run the script.
-- Idempotent: rows are upserted; rows of this version that left the JSON are removed.
-- =============================================================================

insert into outreach_price_book(version, plan, billing_period, step_min, per_account_monthly, stripe_price_lookup_key) values
  ('v1', 'launch', 'monthly', 1, 49, 'launch_monthly_v1'),
  ('v1', 'launch', 'monthly', 5, 39, 'launch_monthly_v1'),
  ('v1', 'launch', 'monthly', 10, 29, 'launch_monthly_v1'),
  ('v1', 'launch', 'monthly', 20, 25, 'launch_monthly_v1'),
  ('v1', 'launch', 'monthly', 50, 22, 'launch_monthly_v1'),
  ('v1', 'launch', 'monthly', 100, 16, 'launch_monthly_v1'),
  ('v1', 'launch', 'quarterly', 1, 44, 'launch_quarterly_v1'),
  ('v1', 'launch', 'quarterly', 5, 35, 'launch_quarterly_v1'),
  ('v1', 'launch', 'quarterly', 10, 26, 'launch_quarterly_v1'),
  ('v1', 'launch', 'quarterly', 20, 23, 'launch_quarterly_v1'),
  ('v1', 'launch', 'quarterly', 50, 20, 'launch_quarterly_v1'),
  ('v1', 'launch', 'quarterly', 100, 14, 'launch_quarterly_v1'),
  ('v1', 'launch', 'annual', 1, 39, 'launch_annual_v1'),
  ('v1', 'launch', 'annual', 5, 31, 'launch_annual_v1'),
  ('v1', 'launch', 'annual', 10, 23, 'launch_annual_v1'),
  ('v1', 'launch', 'annual', 20, 20, 'launch_annual_v1'),
  ('v1', 'launch', 'annual', 50, 18, 'launch_annual_v1'),
  ('v1', 'launch', 'annual', 100, 13, 'launch_annual_v1'),
  ('v1', 'scale', 'monthly', 1, 69, 'scale_monthly_v1'),
  ('v1', 'scale', 'monthly', 5, 49, 'scale_monthly_v1'),
  ('v1', 'scale', 'monthly', 10, 40, 'scale_monthly_v1'),
  ('v1', 'scale', 'monthly', 20, 35, 'scale_monthly_v1'),
  ('v1', 'scale', 'monthly', 50, 30, 'scale_monthly_v1'),
  ('v1', 'scale', 'monthly', 100, 20, 'scale_monthly_v1'),
  ('v1', 'scale', 'quarterly', 1, 62, 'scale_quarterly_v1'),
  ('v1', 'scale', 'quarterly', 5, 44, 'scale_quarterly_v1'),
  ('v1', 'scale', 'quarterly', 10, 36, 'scale_quarterly_v1'),
  ('v1', 'scale', 'quarterly', 20, 32, 'scale_quarterly_v1'),
  ('v1', 'scale', 'quarterly', 50, 27, 'scale_quarterly_v1'),
  ('v1', 'scale', 'quarterly', 100, 18, 'scale_quarterly_v1'),
  ('v1', 'scale', 'annual', 1, 55, 'scale_annual_v1'),
  ('v1', 'scale', 'annual', 5, 39, 'scale_annual_v1'),
  ('v1', 'scale', 'annual', 10, 32, 'scale_annual_v1'),
  ('v1', 'scale', 'annual', 20, 28, 'scale_annual_v1'),
  ('v1', 'scale', 'annual', 50, 24, 'scale_annual_v1'),
  ('v1', 'scale', 'annual', 100, 16, 'scale_annual_v1'),
  ('v1', 'enterprise', 'monthly', 1, 99, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'monthly', 5, 69, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'monthly', 10, 55, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'monthly', 20, 50, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'monthly', 50, 40, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'monthly', 100, 30, 'enterprise_monthly_v1'),
  ('v1', 'enterprise', 'quarterly', 1, 89, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'quarterly', 5, 62, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'quarterly', 10, 50, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'quarterly', 20, 45, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'quarterly', 50, 36, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'quarterly', 100, 27, 'enterprise_quarterly_v1'),
  ('v1', 'enterprise', 'annual', 1, 79, 'enterprise_annual_v1'),
  ('v1', 'enterprise', 'annual', 5, 55, 'enterprise_annual_v1'),
  ('v1', 'enterprise', 'annual', 10, 44, 'enterprise_annual_v1'),
  ('v1', 'enterprise', 'annual', 20, 40, 'enterprise_annual_v1'),
  ('v1', 'enterprise', 'annual', 50, 32, 'enterprise_annual_v1'),
  ('v1', 'enterprise', 'annual', 100, 24, 'enterprise_annual_v1')
on conflict (version, plan, billing_period, step_min) do update
  set per_account_monthly = excluded.per_account_monthly, stripe_price_lookup_key = excluded.stripe_price_lookup_key;

delete from outreach_price_book where version = 'v1' and step_min not in (1, 5, 10, 20, 50, 100);

insert into outreach_plan_features(plan, feature, enabled, limit_value) values
  ('launch', 'ai_auto_reply', false, null),
  ('scale', 'ai_auto_reply', true, null),
  ('enterprise', 'ai_auto_reply', true, null),
  ('launch', 'clients', false, null),
  ('scale', 'clients', true, null),
  ('enterprise', 'clients', true, null),
  ('launch', 'client_viewer', false, null),
  ('scale', 'client_viewer', true, null),
  ('enterprise', 'client_viewer', true, null),
  ('launch', 'client_reports', false, null),
  ('scale', 'client_reports', true, null),
  ('enterprise', 'client_reports', true, null),
  ('launch', 'tracking_domains', false, null),
  ('scale', 'tracking_domains', true, null),
  ('enterprise', 'tracking_domains', true, null),
  ('launch', 'white_label', false, null),
  ('scale', 'white_label', false, null),
  ('enterprise', 'white_label', true, null),
  ('launch', 'webhooks', false, null),
  ('scale', 'webhooks', false, null),
  ('enterprise', 'webhooks', true, null),
  ('launch', 'public_api', false, null),
  ('scale', 'public_api', false, null),
  ('enterprise', 'public_api', true, null),
  ('launch', 'crm_sync', false, null),
  ('scale', 'crm_sync', false, null),
  ('enterprise', 'crm_sync', true, null),
  ('launch', 'priority_processing', false, null),
  ('scale', 'priority_processing', false, null),
  ('enterprise', 'priority_processing', true, null),
  ('launch', 'ai_limits', true, 100),
  ('scale', 'ai_limits', true, 100),
  ('enterprise', 'ai_limits', true, 200),
  ('launch', 'webchat_inboxes', true, 1),
  ('scale', 'webchat_inboxes', true, 3),
  ('enterprise', 'webchat_inboxes', true, null),
  ('launch', 'voice_minutes', false, 0),
  ('scale', 'voice_minutes', true, 100),
  ('enterprise', 'voice_minutes', true, 300),
  ('launch', 'voice_max_minutes', true, 5),
  ('scale', 'voice_max_minutes', true, 10),
  ('enterprise', 'voice_max_minutes', true, 30),
  ('launch', 'voice_concurrency', true, 2),
  ('scale', 'voice_concurrency', true, 5),
  ('enterprise', 'voice_concurrency', true, 10),
  ('launch', 'voice_own_key', false, null),
  ('scale', 'voice_own_key', true, null),
  ('enterprise', 'voice_own_key', true, null)
on conflict (plan, feature) do update set enabled = excluded.enabled, limit_value = excluded.limit_value;

delete from outreach_plan_features where feature not in ('ai_auto_reply', 'clients', 'client_viewer', 'client_reports', 'tracking_domains', 'white_label', 'webhooks', 'public_api', 'crm_sync', 'priority_processing', 'ai_limits', 'webchat_inboxes', 'voice_minutes', 'voice_max_minutes', 'voice_concurrency', 'voice_own_key');

insert into outreach_early_supporter_tiers(tier, spots, discount, coupon) values
  (1, 50, 0.50, 'early_50'),
  (2, 50, 0.30, 'early_30'),
  (3, 50, 0.10, 'early_10')
on conflict (tier) do update set spots = excluded.spots, discount = excluded.discount, coupon = excluded.coupon;

delete from outreach_early_supporter_tiers where tier not in (1, 2, 3);

-- the numbers the billing functions read (trial length, data retention, dunning days)
insert into outreach_flags(key, value) values
  ('billing_price_version', to_jsonb('v1'::text)),
  ('billing_trial_days', to_jsonb(7)),
  ('billing_trial_accounts', to_jsonb(1)),
  ('billing_trial_features_of', to_jsonb('scale'::text)),
  ('billing_trial_data_days', to_jsonb(30)),
  ('billing_cancel_data_days', to_jsonb(90)),
  ('billing_past_due_suspend_day', to_jsonb(7)),
  ('billing_disconnect_paused_after_days', to_jsonb(14)),
  ('billing_max_self_serve_accounts', to_jsonb(100))
on conflict (key) do update set value = excluded.value;
