// GENERATED by scripts/pricing-sync.mjs from pricing/v1.json. Do not edit: change the JSON and run the script.
import type { PriceBook } from "./pricing_core.ts";

export const PRICE_BOOK: PriceBook = {
  "version": "v1",
  "currency": "usd",
  "steps": [
    1,
    5,
    10,
    20,
    50,
    100
  ],
  "max_self_serve_accounts": 100,
  "periods": [
    {
      "id": "monthly",
      "label": "Monthly",
      "months": 1,
      "discount": 0,
      "interval": "month",
      "interval_count": 1
    },
    {
      "id": "quarterly",
      "label": "Quarterly",
      "months": 3,
      "discount": 0.1,
      "interval": "month",
      "interval_count": 3
    },
    {
      "id": "annual",
      "label": "Annual",
      "months": 12,
      "discount": 0.2,
      "interval": "year",
      "interval_count": 1
    }
  ],
  "plans": [
    {
      "id": "launch",
      "name": "Launch",
      "rank": 1,
      "for": "Sales teams at one company",
      "highlights": [
        "LinkedIn, email, Instagram and WhatsApp in one sequence",
        "One inbox for every channel",
        "AI tags every reply",
        "Run it by chat in Claude or ChatGPT",
        "Unlimited sequences",
        "A/B testing",
        "Full reports"
      ],
      "prices": {
        "monthly": [
          49,
          39,
          29,
          25,
          22,
          16
        ],
        "quarterly": [
          44,
          35,
          26,
          23,
          20,
          14
        ],
        "annual": [
          39,
          31,
          23,
          20,
          18,
          13
        ]
      }
    },
    {
      "id": "scale",
      "name": "Scale",
      "rank": 2,
      "for": "Growing teams that want AI to auto-reply to prospects and hand off qualified leads.",
      "highlights": [
        "Everything in Launch, plus:",
        "AI replies and qualifies leads for you",
        "Clients, kept apart",
        "Client-viewer portal",
        "Per-client reports and exports",
        "Custom tracking domains"
      ],
      "prices": {
        "monthly": [
          69,
          49,
          40,
          35,
          30,
          20
        ],
        "quarterly": [
          62,
          44,
          36,
          32,
          27,
          18
        ],
        "annual": [
          55,
          39,
          32,
          28,
          24,
          16
        ]
      }
    },
    {
      "id": "enterprise",
      "name": "Enterprise",
      "rank": 3,
      "for": "Larger agencies and custom stacks",
      "highlights": [
        "Everything in Scale, plus:",
        "White-label on your own domain",
        "Public API and signed webhooks",
        "CRM sync (early access)",
        "Priority processing",
        "Higher AI limits"
      ],
      "prices": {
        "monthly": [
          99,
          69,
          55,
          50,
          40,
          30
        ],
        "quarterly": [
          89,
          62,
          50,
          45,
          36,
          27
        ],
        "annual": [
          79,
          55,
          44,
          40,
          32,
          24
        ]
      }
    }
  ],
  "features": [
    {
      "key": "ai_auto_reply",
      "label": "AI replies sends by itself (Auto mode)",
      "launch": false,
      "scale": true,
      "enterprise": true
    },
    {
      "key": "clients",
      "label": "Clients, kept apart",
      "launch": false,
      "scale": true,
      "enterprise": true
    },
    {
      "key": "client_viewer",
      "label": "Client-viewer portal and logins",
      "launch": false,
      "scale": true,
      "enterprise": true
    },
    {
      "key": "client_reports",
      "label": "Per-client reports and exports",
      "launch": false,
      "scale": true,
      "enterprise": true
    },
    {
      "key": "tracking_domains",
      "label": "Custom tracking domains",
      "launch": false,
      "scale": true,
      "enterprise": true
    },
    {
      "key": "white_label",
      "label": "White-label on your own domain",
      "launch": false,
      "scale": false,
      "enterprise": true
    },
    {
      "key": "webhooks",
      "label": "Signed webhooks",
      "launch": false,
      "scale": false,
      "enterprise": true
    },
    {
      "key": "public_api",
      "label": "Public API",
      "launch": false,
      "scale": false,
      "enterprise": true
    },
    {
      "key": "crm_sync",
      "label": "CRM sync",
      "launch": false,
      "scale": false,
      "enterprise": true
    },
    {
      "key": "priority_processing",
      "label": "Priority processing",
      "launch": false,
      "scale": false,
      "enterprise": true
    },
    {
      "key": "ai_limits",
      "label": "AI limits",
      "launch": true,
      "scale": true,
      "enterprise": true,
      "limits": {
        "launch": 100,
        "scale": 100,
        "enterprise": 200
      },
      "limit_unit": "percent of the standard AI allowance"
    },
    {
      "key": "webchat_inboxes",
      "label": "Website chat inboxes",
      "launch": true,
      "scale": true,
      "enterprise": true,
      "limits": {
        "launch": 1,
        "scale": 3,
        "enterprise": null
      }
    },
    {
      "key": "voice_minutes",
      "label": "Voice minutes for the website agent",
      "launch": false,
      "scale": true,
      "enterprise": true,
      "limits": {
        "launch": 0,
        "scale": 100,
        "enterprise": 300
      },
      "limit_unit": "minutes a month"
    },
    {
      "key": "voice_max_minutes",
      "label": "Longest voice call",
      "launch": true,
      "scale": true,
      "enterprise": true,
      "limits": {
        "launch": 5,
        "scale": 10,
        "enterprise": 30
      },
      "limit_unit": "minutes"
    },
    {
      "key": "voice_concurrency",
      "label": "Voice calls at the same time",
      "launch": true,
      "scale": true,
      "enterprise": true,
      "limits": {
        "launch": 2,
        "scale": 5,
        "enterprise": 10
      }
    },
    {
      "key": "voice_own_key",
      "label": "Your own ElevenLabs account for voice (no minute cap)",
      "launch": false,
      "scale": true,
      "enterprise": true
    }
  ],
  "trial": {
    "days": 7,
    "accounts": 1,
    "features_of": "scale",
    "data_kept_days": 30
  },
  "cancellation": {
    "data_kept_days": 90,
    "warn_days_before_deletion": [
      30,
      7,
      1
    ]
  },
  "past_due": {
    "reminder_day": 3,
    "suspend_day": 7
  },
  "hygiene": {
    "disconnect_billing_paused_after_days": 14,
    "swap_alert_per_month": 5
  },
  "early_supporter": {
    "tiers": [
      {
        "tier": 1,
        "spots": 50,
        "discount": 0.5,
        "coupon": "early_50"
      },
      {
        "tier": 2,
        "spots": 50,
        "discount": 0.3,
        "coupon": "early_30"
      },
      {
        "tier": 3,
        "spots": 50,
        "discount": 0.1,
        "coupon": "early_10"
      }
    ]
  }
};
