#!/usr/bin/env node
// One source of prices (pricing-billing-PRD §11.4): pricing/v1.json.
// This script copies it into the two places that cannot read the JSON at run time:
//   supabase/functions/_shared/outreach/pricing.gen.ts   (edge functions are bundled from supabase/functions only)
//   migrations/outreach/058_billing_seed.sql             (outreach_price_book + outreach_plan_features rows)
//
//   node scripts/pricing-sync.mjs            write both files
//   node scripts/pricing-sync.mjs --check    exit 1 when either file is out of date (run in CI / before a deploy)
//
// The web app imports the JSON directly (lib/outreach/pricing.ts); scripts/stripe-setup.ts reads it too.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const book = JSON.parse(readFileSync(join(root, 'pricing/v1.json'), 'utf8'));

// --- sanity: the book must be internally consistent before anything is generated from it -------------------------------
const fail = (m) => { console.error(`pricing/v1.json: ${m}`); process.exit(1); };
if (!/^v\d+$/.test(book.version)) fail('version must look like v1');
const steps = book.steps;
if (!Array.isArray(steps) || steps[0] !== 1 || steps.some((s, i) => i > 0 && s <= steps[i - 1])) fail('steps must start at 1 and increase');
const monthly = book.periods.find((p) => p.id === 'monthly');
if (!monthly) fail('a monthly period is required');
for (const plan of book.plans) {
  for (const period of book.periods) {
    const row = plan.prices[period.id];
    if (!Array.isArray(row) || row.length !== steps.length) fail(`${plan.id}.${period.id} needs ${steps.length} prices`);
    row.forEach((v, i) => {
      if (!Number.isInteger(v) || v <= 0) fail(`${plan.id}.${period.id}[${i}] must be a whole dollar amount`);
      // the website's listPerSender(): the monthly price less the period discount, rounded to the dollar
      const want = Math.round(plan.prices.monthly[i] * (1 - period.discount));
      if (v !== want) fail(`${plan.id}.${period.id}[${i}] is ${v}, expected ${want} (monthly ${plan.prices.monthly[i]} less ${period.discount * 100}%)`);
      if (i > 0 && v > row[i - 1]) fail(`${plan.id}.${period.id}: the per-account price must not rise with more accounts`);
    });
  }
}
for (const f of book.features) for (const plan of book.plans) if (typeof f[plan.id] !== 'boolean') fail(`feature ${f.key} needs true/false for ${plan.id}`);

// --- 1. edge-function copy --------------------------------------------------------------------------------------------------
const gen = `// GENERATED by scripts/pricing-sync.mjs from pricing/${book.version}.json. Do not edit: change the JSON and run the script.
import type { PriceBook } from "./pricing_core.ts";

export const PRICE_BOOK: PriceBook = ${JSON.stringify(book, null, 2)};
`;

// --- 2. database seed -------------------------------------------------------------------------------------------------------
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const priceRows = [];
for (const plan of book.plans) for (const period of book.periods) steps.forEach((s, i) => {
  priceRows.push(`  (${q(book.version)}, ${q(plan.id)}, ${q(period.id)}, ${s}, ${plan.prices[period.id][i]}, ${q(`${plan.id}_${period.id}_${book.version}`)})`);
});
const featureRows = [];
for (const f of book.features) for (const plan of book.plans) {
  const lim = f.limits ? f.limits[plan.id] : null;
  featureRows.push(`  (${q(plan.id)}, ${q(f.key)}, ${f[plan.id]}, ${lim == null ? 'null' : lim})`);
}
const tierRows = book.early_supporter.tiers.map((t) => `  (${t.tier}, ${t.spots}, ${t.discount.toFixed(2)}, ${q(t.coupon)})`);
const sql = `-- =============================================================================
-- Outreach Platform — 058 billing v2: price book, plan features and early-supporter tiers
-- GENERATED by scripts/pricing-sync.mjs from pricing/${book.version}.json. Do not edit: change the JSON and run the script.
-- Idempotent: rows are upserted; rows of this version that left the JSON are removed.
-- =============================================================================

insert into outreach_price_book(version, plan, billing_period, step_min, per_account_monthly, stripe_price_lookup_key) values
${priceRows.join(',\n')}
on conflict (version, plan, billing_period, step_min) do update
  set per_account_monthly = excluded.per_account_monthly, stripe_price_lookup_key = excluded.stripe_price_lookup_key;

delete from outreach_price_book where version = ${q(book.version)} and step_min not in (${steps.join(', ')});

insert into outreach_plan_features(plan, feature, enabled, limit_value) values
${featureRows.join(',\n')}
on conflict (plan, feature) do update set enabled = excluded.enabled, limit_value = excluded.limit_value;

delete from outreach_plan_features where feature not in (${book.features.map((f) => q(f.key)).join(', ')});

insert into outreach_early_supporter_tiers(tier, spots, discount, coupon) values
${tierRows.join(',\n')}
on conflict (tier) do update set spots = excluded.spots, discount = excluded.discount, coupon = excluded.coupon;

delete from outreach_early_supporter_tiers where tier not in (${book.early_supporter.tiers.map((t) => t.tier).join(', ')});

-- the numbers the billing functions read (trial length, data retention, dunning days)
insert into outreach_flags(key, value) values
  ('billing_price_version', to_jsonb(${q(book.version)}::text)),
  ('billing_trial_days', to_jsonb(${book.trial.days})),
  ('billing_trial_accounts', to_jsonb(${book.trial.accounts})),
  ('billing_trial_features_of', to_jsonb(${q(book.trial.features_of)}::text)),
  ('billing_trial_data_days', to_jsonb(${book.trial.data_kept_days})),
  ('billing_cancel_data_days', to_jsonb(${book.cancellation.data_kept_days})),
  ('billing_past_due_suspend_day', to_jsonb(${book.past_due.suspend_day})),
  ('billing_disconnect_paused_after_days', to_jsonb(${book.hygiene.disconnect_billing_paused_after_days})),
  ('billing_max_self_serve_accounts', to_jsonb(${book.max_self_serve_accounts}))
on conflict (key) do update set value = excluded.value;
`;

const targets = [
  ['supabase/functions/_shared/outreach/pricing.gen.ts', gen],
  ['migrations/outreach/058_billing_seed.sql', sql],
];
let stale = 0;
for (const [rel, content] of targets) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) { console.log(`ok       ${rel}`); continue; }
  if (check) { console.error(`STALE    ${rel} (run: node scripts/pricing-sync.mjs)`); stale++; continue; }
  writeFileSync(path, content);
  console.log(`written  ${rel}`);
}
if (stale) process.exit(1);
